### ISSUE TITLE
[Question] Does this help make it easier to build offline app and also with syncing with a centralized database?

### ISSUE THREAD

**Issue by simkimsia** [jlongster/absurd-sql#3]
I read the blogpost https://jlongster.com/future-sql-web and i suppose absurd makes it way faster to read and write to IndexedDB for offline web apps.

But I guess, syncing with centralized database like a postgres, is out of scope for this.

AM I right?

**Comment by jlongster** [comment]
That is out of scope for this, yes. It's up to you to still figure out how to send changes to some kind of service that helps sync. In the future, if someone proposes a need to expose certain methods to help with that, I'd be happy to work with them.

This just persists it locally; I recommend something like CRDTs to actually communicate changes in a way that can be synced.
