### ISSUE TITLE
Kudos and a question

### ISSUE THREAD

**Issue by sydbarrett74** [jlongster/absurd-sql#5]
First, I just wanted to say: WOW. Thank you for all your hard and brilliant work on this.

Second, my question: do you think this could replace MySQL as far as Wordpress goes? One of the pain-points in my maintenance of several WP sites is the performance issues and quirks of admining MySQL instances. Obviously, it would be a lot of effort for someone (or a group of someones) to substitute absurd since WP seems to be largely MySQL-specific, but with all the sites out there that use WP as a CMS, the gains could be substantial.

**Comment by acorncom** [comment]
@sydbarrett74 in theory it might be something that could be done, but in practice it doesn’t seem feasible. The point of this is to have a database in the browser (not on the server) with syncing to a server / other clients left to the author. Wordpress is heavily built around the idea of a server and the syncing part wouldn’t be simple. So don’t hold your breath 😉

**Comment by jlongster** [comment]
Yeah, the Wordpress use case is quite different. You don't really want to have to download every single blog post when hitting a blog just to render one post. In that case you don't want to download all the data.

This is more for **apps** that are supposed to built locally.
