### ISSUE TITLE
Discussion regarding performance / absurd

### ISSUE THREAD

**Issue by linegel** [jlongster/absurd-sql#6]
Since this implementation consistently beats IndexedDB implementation AND provides a consistent syntax for SQLite operation (e.g. you may use same-way defined operations like in an electron app) isn't that implementation is actually absurd?

Good use cases seem pretty clear to me
In case there some another, a well-maintained project for the same purpose, maybe it would be good to add a link to that repo in the description?

**Comment by jlongster** [comment]
The code itself is not absurd, but the fact that it's needed at all and that we're stuck with something like IndexedDB is, and the fact that it beats it so handedly. Don't read too much in the name :)

There's only one other project that I know of that's attempted a similar thing, but it's not quite as fleshed out and proven yet, and doesn't have as much optimizations: https://github.com/rhashimoto/wa-sqlite

**Comment by linegel** [comment]
@jlongster I opened this issue just to have some fun but after reading README and running perf tests on my own I realized that there in no jokes happening in this repo, that's something that people could actually use in a real production environment to improve how their apps work. So please, just consider choosing another name for repo just to prevent misunderstanding of people about the goal of your project. 

And thanks for all that stuff you did!
