### ISSUE TITLE
Browser requirements (iOS lockdown mode)

### ISSUE THREAD

**Issue by CharlieMK** [jlongster/absurd-sql#67]
I'm currently using Actual Budget, and I'm a big fan. 
However, the web app does not work when in [iOS lockdown mode](https://discord.com/channels/937901803608096828/1139056081490948149/1139056081490948149). 

I'm trying to find out why. What I tried:
- the Actual domain is fully whitelisted in iOS - basically this means the fact that I have lockdown mode enabled, should not have any impact. 
- typeof SharedArrayBuffer returns a value - so this should not be a problem
- the error I get in Actual is 'no native wasm support detected' . This is the same error as shown by https://sql.js.org/examples/GUI/index.html **when not whitelisted**. However, after whitelisting the sql.js domain, **that demo works as designed**. This leads me to believe WASM support is there when a domain is whitelisted. 
- your [demo](https://priceless-keller-d097e5.netlify.app/) never works in Safari in iOS lockdown, even when whitelisting it. 
- Actual never works in Safari in iOS lockdown, even when whitelisting it. It keeps returning 'no native wasm support detected'. 
- According to https://wasm-feature-detect.surma.technology/, the same WASM features are available (tested in Safari on a locked down iPad and in Safari on a non-locked down iPad - same results)

Any clues as to what is done differently? I understand this is a case you probably do not wish to support, but I'm very curious what is blocking this library from functioning in iOS in lockdown mode. Maybe it has nothing do with WASM. I have changed the title to 'browser requirements' as I would like to understand which browser features (such as WASM) are required for this library to work. 

_Also see discussion in the Actual Discord channel here: https://discord.com/channels/937901803608096828/1139056081490948149_

**Comment by CharlieMK** [comment]
Problem solved: just use sql-asm.js instead of sql-wasm.js for browsers that do not support web assembly.

**Comment by mattbishop** [comment]
Can you consider using a better term to describe access control other than "whitelist"? It's not very precise given the use of colors. Not everybody knows what "white" is supposed to indicate. 

https://inclusivenaming.org/word-lists/tier-1/whitelist/
